### ISSUE TITLE
How to install PDAL package in python through conda

### ISSUE THREAD

**Issue by niranjanreddy891** [PDAL/python#1]
Please guide me how to install PDAL. I am using win-7 64bit. I used this command `conda install -c mathieu pdal` to install. But it didn't worked. Thanks in advance

**Comment by chambbj** [comment]
This package does not currently have an official condo recipe. The recipe you've referenced is located [here](https://github.com/mathieu1/pcl-stack). If it's not working for you, I'd recommending filing a [ticket](https://github.com/mathieu1/pcl-stack/issues/new) with the author.

If you have PDAL installed, along with Python and few dependencies (python, bumpy, packaging, setup tools), you should be able to run `python setup.py install` to install the PDAL package maintained in this repo.

**Comment by chambbj** [comment]
I have possibly good news for you. We have released a conda package through conda-forge. See [here](https://anaconda.org/conda-forge/pdal) for more information. It can be installed with

```
conda install -c conda-forge pdal
```

Here are some caveats for you based on some of the other issues you've raised elsewhere.

- The conda package does not (yet anyway) include PCL.
- The conda package includes the Python _plugin_ (`filters.python`) but not the Python package (`import pdal`) (this is a work in progress that I would expect to be released in the coming days)

**Comment by chambbj** [comment]
@niranjanreddy891 If you have legitimate concerns that the PDAL Conda package is broken, then please report detailed information about what you've tried at https://github.com/conda-forge/pdal-feedstock. There is a template for reporting your issue. **Please use it!**

If you are simply stating that you cannot install the PDAL Python package via Conda, then you are going to have to be patient. It is not released. No one has said that is released. And it was not ever the focus of this ticket as far as I can tell.

**Comment by hobu** [comment]
@niranjanreddy891 Please stop contacting our projects about this issue. This includes PDAL, PDAL/Python, libLAS, and laspy email lists, ticket tracking, or github repositories. If you cannot figure out how to do this by yourself, you are going to have to pay someone to help you.
