### ISSUE TITLE
JSON pipeline: Unable to parse pipeline

### ISSUE THREAD

**Issue by Hutch07** [PDAL/python#10]
I am using the PDAL.io example to try PDAL with python for the first time.  I am running windows 10 and python 3.5

```
json = """
{
  "pipeline": [
    "C:\HarvardTest\hlt1.las",
    {
        "type": "filters.sort",
        "dimension": "X"
    }
  ]
}"""

import pdal, sys
sys.path.append("C:\\Anaconda\\pkgs\\pdal-1.7.1-py35_vc14h5d9141f_9\\Library\\lib")

pipeline = pdal.Pipeline(json)
pipeline.loglevel = 8 #really noisy
pipeline.validate()
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log
print(metadata)
```

### Output
_Traceback (most recent call last):
  File "thinLaz.py", line 17, in <module>
    pipeline.validate()
  File "C:\Anaconda\lib\site-packages\pdal\pipeline.py", line 42, in validate
    return self.p.validate()
  File "pdal\libpdalpython.pyx", line 93, in pdal.libpdalpython.PyPipeline.validate
RuntimeError: JSON pipeline: Unable to parse pipeline:
* Line 4, Column 5
  Bad escape sequence in string
See Line 4, Column 10 for detail._

I think it might be from the input file directory "C:\\HarvardTest\\hlt1.laz"   I have also tried single backslashes.

**Comment by hobu** [comment]
Please try

```C:\\HarvardTest\\hlt1.las",```

or

```C:/HarvardTest/hlt1.las",```

and report your results.

**Comment by guemilgm** [comment]
Double back slash did the trick for me.
Thanks!
