### ISSUE TITLE
Make 'plugins' an optional install

### ISSUE THREAD

**Issue by hobu** [PDAL/python#100]
The `filters.python` and `readers.numpy` PDAL plugins should be an optional installation.

**Comment by gsakkis** [comment]
@hobu should there be a single option to specify both plugins (`pdal[plugins]`), a separate option for each (`pdal[filters.python]`, `pdal[readers.numpy]`) or all three?

**Comment by hobu** [comment]
pdal[plugins] should be good enough

**Comment by hobu** [comment]
Now moved to https://pypi.org/project/pdal-plugins/ for PDAL-Python 3.0.0+ with their own versioning going forward.
