### ISSUE TITLE
pdal.Pipeline no longer has json kwarg

### ISSUE THREAD

**Issue by j9ac9k** [PDAL/python#119]
Filing at @hobu 's request

In the python PDAL bindings, it appears the current version (3.1.2) does not know about the json keyword argument

```python
>>> import pdal
>>> pdal.__version__
'3.1.2'
>>> dummy = [{"a", "b"}]
>>> pdal.Pipeline(json=dummy)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'json'
>>>
```

**Comment by gsakkis** [comment]
The functionality is still there, it's just renamed to [spec](https://github.com/PDAL/python/blob/master/pdal/pipeline.py#L28) since the first parameter accepts more than json strings now.
