### ISSUE TITLE
Expose `Pipeline._get_json()` as pubic method

### ISSUE THREAD

**Issue by danleesmith** [PDAL/python#123]
Filing ticket as per @hobu's [Gitter request](https://gitter.im/PDAL/PDAL).

The [Pipeline._get_json()](https://github.com/PDAL/python/blob/772bcf0b25abaefe85029be80d4df0b08d74da66/pdal/pipeline.py#L109) method is useful for writing out JSON pipeline strings from constructed pipelines and should be a made public.

**Proposal:**
In `./pdal/pipeline.py` change
```python
def _get_json(self) -> str:
        ...
```
to
```python
def get_json(self) -> str:
        ...
```

**Comment by hobu** [comment]
I would propose we would alias `._get_json` to `toJSON` to follow conventions and make it clear that you're getting a serialization back.
