### ISSUE TITLE
Can't import pdal on Windows

### ISSUE THREAD

**Issue by ssfabiopicchi** [PDAL/python#132]
PDAL version - 2.3.0
python-pdal - 3.0.2

If I try to simply `import pdal` in windows I get a JSONDecodeError. After some investigation I found out that the output of `pdal --drivers --showjson` is cut short.

Curiously, running the command above straight in the command line gives you the full output, but pushing it to a file with `> drivers.json` gives you a cropped json in the same way the subprocess call with `capture_output` is giving.

This is probably some Windows silliness, but I am not super familiar with its internals and couldn't figure it out, so I'm opening the issue to raise this up to someone more knowledgeable than me.

Thanks!

PS Updating python-pdal to 3.2.0 made it worse. `import pdal` simply crashes the REPL

**Comment by hobu** [comment]
Please try with a fresh/clean environment and reopen if this is still an issue.
