### ISSUE TITLE
How do you use the "pdal info file.laz" capabilities using the Python Library?

### ISSUE THREAD

**Issue by robertwood62** [PDAL/python#134]
I see documentation on using pdal "pipeline", but what about using the pdal "info" capabilities?  Is there any documentation on how to get that kind of information?

**Comment by hobu** [comment]
You could add [filters.info](https://pdal.io/en/stable/stages/filters.info.html) to the pipeline and fetch the `.metadata` member afterward. Please use the mailing list for questions.
