### ISSUE TITLE
Get readers.las metadata without executing pipeline

### ISSUE THREAD

**Issue by wonder-sk** [PDAL/python#135]
It would be useful to get access to LAS/LAZ metadata through python bindings - like what `pdal info --metadata` reports (without actually reading points).

Currently stage's metadata are only available after its pipeline gets executed.

`quickinfo` only reports a subset of information (e.g. extent), but does not include things like dataformat ID or XYZ offset/scale.

**Comment by hobu** [comment]
https://github.com/PDAL/PDAL/pull/3897 implementing in PDAL

**Comment by hobu** [comment]
PDAL 2.5.0+ will have support for putting reader metadata into `.quickinfo`.
