### ISSUE TITLE
Wrong location for filters.python and readers.numpy drivers

### ISSUE THREAD

**Issue by ClementAlba** [PDAL/python#143]
Hi,

There is a little problem with the conda package `python-pdal`. Indeed, when I installed this package in a new env (with nothing inside of it) and tried to process a pdal pipeline containing a filters.python stage, I get this error : 

```
PDAL: Couldn't create filter stage of type 'filters.python'.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load.  Please see the FAQ at https://pdal.io/faq
```

When the package is installed, the filters.python and readers.numpy drivers are stored in `%CONDA_PREFIX%\bin`, however the `%PDAL_DRIVER_PATH%` variable have this value : 

```
(test_pypdal) C:\>echo %CONDA_PREFIX%
D:\applications\miniforge3\envs\test_pypdal

(test_pypdal) C:\>echo %PDAL_DRIVER_PATH%
D:\applications\miniforge3\envs\test_pypdal\Library\bin;D:\applications\miniforge3\envs\test_pypdal\lib\site-packages\bin
```

So the drivers for filters.python and readers.numpy are not found. I was able to fix this problem by changing the value of the PDAL_DRIVER_PATH variable : 

```
set PDAL_DRIVER_PATH=%CONDA_PREFIX%\bin
```

Is it a normal behavior ?

**PS**: I'm on Windows 10 and I use conda 22.9.0

**Comment by hobu** [comment]
Same issue as #139
