### ISSUE TITLE
Pdal tile procedure dropping 0.01% of points

### ISSUE THREAD

**Issue by kcotar** [PDAL/python#146]
We have noticed a consistent behaviour that the tile command drops 0.01% of all input points during the tiling procedure. If I reproject points from tiled files back to the original files and mark "missing" points, a consistent pattern appears. The missing points have indices 9999, 19999, 29999, etc. This looks like an off-by-one error somewhere in pdal tile stream data reader or tile writer, where the reader reads 10k points per batch. This is probably a quick fix, but I lack the knowledge about the pdal architecture to tackle.

**Comment by hobu** [comment]
> the tile command 

If this is an issue with `pdal tile` it needs to be made in https://github.com/PDAL/PDAL/

Without an example scenario, this issue is unlikely to be picked up. If you can do the legwork to provide a concrete scenario, it will likely be addressed.
