### ISSUE TITLE
【Install Error】I can't use pip to install pdal, can you help me?

### ISSUE THREAD

**Issue by SeanSiyang** [PDAL/python#152]
Hi, 
my operating system is Windows, and my Python version is 3.7.
When I use pip to install PDAL, I will encounter errors like the following:
```bash
Collecting numpy (from pdal)
  Using cached https://mirrors.aliyun.com/pypi/packages/69/65/0d47953afa0ad569d12de5f65d964321c208492064c38fe3b0b9744f8d44/numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
Building wheels for collected packages: pdal
  Building wheel for pdal (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pdal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [272 lines of output]
      Please see CMake's output for more information.

......

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pdal
Failed to build pdal
ERROR: Could not build wheels for pdal, which is required to install pyproject.toml-based projects
```

I switched to Linux system and still cannot install it. Can you help me?

Have a nice day~

**Comment by SeanSiyang** [comment]
When I use the command as follows can be work:
```bash
conda install -c conda-forge pdal python-pdal gdal
```
I don't know why the pip tools can not work :)

**Comment by hobu** [comment]
> I don't know why the pip tools can not work :)

Installation of the PDAL Python bindings requires the main PDAL library also be installed. We do not provide wheels, we are not going to provide wheels, and we will wait for Python Land to come up with whatever is better than wheels and *maybe* do that when the time comes.
