### ISSUE TITLE
Getting Spatial Reference via quickinfo from a LAZ

### ISSUE THREAD

**Issue by CharlesGaydon** [PDAL/python#154]
I gather from different PR and issues that a pipeline involving a `pdal.Filter.las` reader should give me access to the point cloud metadata. For instance theses issues
- [Get readers.las metadata without executing pipeline #135](https://github.com/PDAL/python/issues/135) and [this reply in particular](https://github.com/PDAL/python/issues/135#issuecomment-1328442592) that says
> PDAL 2.5.0+ will have support for putting reader metadata into .quickinfo.
- [How to pass SRS and other metadata from one pipeline to another #112](https://github.com/PDAL/python/issues/112)

And this PR:
- [add metadata to quickinfo and implement for readers.las #3897](https://github.com/PDAL/PDAL/pull/3897)

But with quickinfo I only get a subset of the information that would be expected in the metadata.
```
r = pdal.Reader.las(filename=input_file)
p = r.pipeline()
p.quickinfo

RESULT: 
{'readers.las': {'bounds': {...}, 'dimensions': 'X, Y, Z, Intensity, ..., Infrared', 'num_points': 51369}}
```
Am I missing something?

I am currently using [the ugly workaround described here](https://github.com/PDAL/python/pull/109#issue-1116713655) where I call `pdal --info` via subprocess to get the LAZ metadata and, eventually, its projection from `metadata["comp_spatialreference"]`

Current versions:
```
pdal                      2.5.5                hee5d408_0    conda-forge
pdal-plugins              1.2.0                    pypi_0    pypi
python-pdal               3.2.3           py310h8245ec1_2    conda-forge
```

**Comment by hobu** [comment]
I'm not quite sure what you're asking here. You can't get all of the metadata from `.quickinfo`. You can only get the full metadata of a file or a pipeline by actually executing it. Can you provide some more detail about what you see is the issue? 



In your example above ...

```
count = p.execute()
metadata = p.metadata
```
