### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by maboualidev** [PDAL/python#158]
On a fresh environment, when doing 

```bash
pip install pdal
```

the following error is generated:

```bash
 CMake Error at CMakeLists.txt:26 (find_package):
        By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "PDAL", but
        CMake did not find one.

        Could not find a package configuration file provided by "PDAL" (requested
        version 2.5) with any of the following names:

          PDALConfig.cmake
          pdal-config.cmake

        Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
        "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
        provides a separate development package or SDK, be sure it has been
        installed.


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-0nwioa9w/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-0nwioa9w/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
```

Hence, the package is not installed via pip.

**Comment by hobu** [comment]
> On a fresh environment, when doing

You need to install the PDAL base library. The Python bindings do not automatically install this for you.

**Comment by maboualidev** [comment]
closing this one as a new one is created #159

**Comment by maboualidev** [comment]
Which one is th PDAL base library? `pip install xxx`. What is the 'xxx' for base library?

**Comment by hobu** [comment]
The PDAL base library is a C++ library that you will need to install. If you are using Conda Forge, it is called `pdal` and the Python bindings are called `python-pdal`. If you're using some distribution or build system you're on your own.

**Comment by maboualidev** [comment]
So, would `pip install python-pdal` get the base library installed. 

Side note: I am using an internal build system and I am not able to use `conda`.

**Comment by hobu** [comment]
> Side note: I am using an internal build system and I am not able to use conda.

>>  If you're using some distribution or build system you're on your own.

**Comment by maboualidev** [comment]
On a regular system, NOT USING the internal build system, I did this:

```bash
pip install python-pdal
pip install pdal
```

still same error. 

is there a way to install it only PIP? and not conda at all?

**Comment by hobu** [comment]
https://www.google.com/search?q=pdal+compilation

**Comment by maboualidev** [comment]
ok; seems the answer is no then. Either Conda or compile
