### ISSUE TITLE
ImportError with undefined symbol _ZN4pdal6Config16debugInformationB5cxx11Ev

### ISSUE THREAD

**Issue by weiji14** [PDAL/python#16]
Hi there,

I am reporting an issue when importing pdal using python. The pdal binaries are installed via conda, while PDAL is installed using pip inside the conda environment.

Steps to reproduce:

```bash
conda create -n pdal-bug pdal=1.8.0
conda activate pdal-bug
pip install Cython==0.29 packaging==18.0
pip install PDAL==2.1.0
python -c "import pdal"
```

Error message:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/miniconda3/envs/pdal-bug/lib/python3.6/site-packages/pdal/__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File "/home/user/miniconda3/envs/pdal-bug/lib/python3.6/site-packages/pdal/pipeline.py", line 2, in <module>
    from pdal import libpdalpython
ImportError: /home/user/miniconda3/envs/pdal-bug/lib/python3.6/site-packages/pdal/libpdalpython.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4pdal6Config16debugInformationB5cxx11Ev
```

I'm not familiar with CPython., but my suspicion is that it is related to these 2 lines at https://github.com/PDAL/python/blame/bc88cca063f37e471538da31432b62134b93a999/pdal/libpdalpython.pyx#L35-L36.

**Comment by hobu** [comment]
Which platform? I was able to successfully follow your example on OSX.

**Comment by weiji14** [comment]
Linux 64-bit.

**Comment by hobu** [comment]
ABI issue due to conda. The extension needs to be compiled with  `D_GLIBCXX_USE_CXX11_ABI=1` defined. I'm not sure how to do this automatically.

**Comment by weiji14** [comment]
So this is an upstream issue? Is it with https://github.com/conda-forge/python-pdal-feedstock or https://github.com/conda-forge/pdal-feedstock/?

**Comment by hobu** [comment]
python-pdal-feedstock needs to set that when it compiles

**Comment by weiji14** [comment]
Looking at the python-pdal feedstock's [meta.yaml](https://github.com/conda-forge/python-pdal-feedstock/blob/master/recipe/meta.yaml) file, it seems to link back to this very repository? See [source and build lines](https://github.com/conda-forge/python-pdal-feedstock/blame/master/recipe/meta.yaml#L9-L17).

I've had a look at the setup.py file here and noticed this [extra_compile_args](https://github.com/conda-forge/python-pdal-feedstock/blame/master/recipe/meta.yaml#L9-L17) part. My uneducated guess is that passing in the `D_GLIBCXX_USE_CXX11_ABI=0` parameter there might work.

Some other references I've been reading:

- https://github.com/conda-forge/docker-images/pull/22
- https://github.com/conda-forge/conda-forge.github.io/issues/388
- https://groups.google.com/forum/#!topic/bob-devel/Ud5MYSofHmw
- https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

I'll try to see if I can get `import pdal` to work by compiling pdal-python with that flag through setup.py. Not sure how this change will affect other users though, I don't quite understand what I'm doing :laughing:

**Comment by hobu** [comment]
Yes the recipe needs to be tweaked.
