### ISSUE TITLE
Install from pypi for win64

### ISSUE THREAD

**Issue by sehHeiden** [PDAL/python#166]
I am trying to install PDAL to use with Python3 with my requirements.txt with pip on Windows11.

Using Python 3.11.8.

Steps:
1) I installed Visual Studio (for the C-Compiler)
2) Installed C-Make (Added to Path)
3) Restated the PC several times.

Still I get this error:

> Detecting CXX compile features - done
>       -- Found Python3: .../venv/Scripts/python.exe (found version "3.11.8") found components: Interpreter Development.Module NumPy
>       CMake Error at CMakeLists.txt:26 (find_package):
>         By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
>         asked CMake to find a package configuration file provided by "PDAL", but
>         CMake did not find one.
> 
>         Could not find a package configuration file provided by "PDAL" (requested
>         version 2.5) with any of the following names:
> 
>           PDALConfig.cmake
>           pdal-config.cmake
> 
>         Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
>         "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
>         provides a separate development package or SDK, be sure it has been
>         installed.

Do I need anything else before installing with pip?

**Comment by hobu** [comment]
> Do I need anything else before installing with pip?

You need the PDAL library installed. It does not come with the Python packages and there are no binary wheels with it.

**Comment by hobu** [comment]
a. Done in https://github.com/PDAL/python/pull/165/commits/f065148cab68209d49614c850c0f829620e0af49 to be included in the next PDAL Python bindings release.

b. No. You are welcome to provide patches to build config and cibuildwheel that construct wheels on Windows for PDAL and the PDAL Python bindings, demonstrate commitment to the project to maintain them going forward, and be prepared to answer any and all support help issues that arise from the DLL hell put upon users by binary wheels for projects with extensive dependencies like PDAL and GDAL.
