### ISSUE TITLE
Pipelines from dictionaries?

### ISSUE THREAD

**Issue by mccarthyryanc** [PDAL/python#21]
I frequently want to pull pointclouds into numpy arrays, but don't have a JSON pipeline already formatted. What I end up doing is building the pipeline as dict and the calling `json.dumps` to feed into `pdal.Pipeline`.

I created a [branch](https://github.com/weyerhaeuser/python/tree/dict-pipeline) that extends this idea a bit, so you can do things like:
```python
import pdal
pl = pdal.Pipeline()
pl.add_file('file.las')
pl.add_crop(bounds=(0,0,100,100))
pl.create()
pl.validate()
pl.execute()
```

If this is useful I can clean it up, add more tests, or submit a pull request.

**Comment by hobu** [comment]
For now, we have purposely abstained from exposing the object hierarchy of PDAL into the Python bindings. The rationale for this choice is PDAL is very careful to protect the backward compatibility of the JSON, but we have moved around the objects and accessors from time to time. 

A patch that provides this kind of object convenience in pure python land could be useful.

**Comment by hobu** [comment]
The new API provided in PDAL Python 3.0.0 will have full support for streaming and incremental pipeline construction using Python objects thanks to @gsakkis and TileDB.
