### ISSUE TITLE
memory leak when calling pdal.Pipeline

### ISSUE THREAD

**Issue by AndreasDL** [PDAL/python#23]
**Description**
For each bpf file in a folder, i need to get the first GpsTime.

I wrote a function that does this, so far so good. 
But when i start looping, i notice that **the memory is not cleared after the pdal.Pipeline method**. Am I missing something ? or is this a memory leak ? I tried setting the pipeline to None and calling del pipeline explicitly. 

The script and output below demonstrate what I mean. This is the first issue I raise to an open source repo, if you need more information, please ask.

**Script** (with basic memory profiling):
``` python
import os
import json
import pdal

import psutil
def get_process_memory():
    process = psutil.Process(os.getpid())
    return process.memory_info().rss
def track(func):
    def wrapper(*args, **kwargs):
        mem_before = get_process_memory()
        result = func(*args, **kwargs)
        mem_after = get_process_memory()
        print("{}: memory before: {:,}, after: {:,}, consumed: {:,}".format(
            func.__name__,mem_before, mem_after, mem_after - mem_before))
        return result
    return wrapper

@track
def getGpsTime(fname):
    pipeline_definition = {
        'pipeline': [
            {
                'type': 'readers.bpf',
                'filename': fname
            }
        ]
    }
    pipeline = pdal.Pipeline(json.dumps(pipeline_definition))
    pipeline.validate()
    pipeline.execute()
    return int(pipeline.arrays[0]['GpsTime'][0])

if __name__ == "__main__":
    folder = "/tmp/tmp_split/"
    for f in os.listdir(folder):
        fname = folder + f
        print(fname, " => ", getGpsTime(fname))
```

**Output**
```
getGpsTime: memory before: 56,717,312, after: 831,414,272, consumed: 774,696,960
/tmp/tmp_split/1.bpf  =>  0
getGpsTime: memory before: 831,414,272, after: 839,520,256, consumed: 8,105,984
/tmp/tmp_split/2.bpf  =>  1704964
```
as you can see the memory keeps growing, which is causing out of memory errors when i batch process.

**Comment by AndreasDL** [comment]
possible work around => run the function on a separate thread

**Comment by jrobichaud** [comment]
We noticed the same problem but the problem occurs when using the `pipeline.arrays` like you do.

**Comment by jrobichaud** [comment]
Someone appears to have spotted the bug a while ago. A comment from before the python project was moved to its own repository.

```c++
   for (auto i: pvset)
    {
        //ABELL - Leak?
        Array *array = new python::Array;
        array->update(i);
        output.push_back(array);
    }
```
https://github.com/PDAL/python/blob/master/pdal/PyPipeline.cpp#L168

**Comment by jrobichaud** [comment]
@abellgithub ?

**Comment by WouterDX** [comment]
@AndreasDL Did the fix mentioned here help you in your problem?
One another approach I'm looking at: what happens if you return a copy, eg
`return int(pipeline.arrays[0]['GpsTime'][0].copy())`

**Comment by AndreasDL** [comment]
The fixed solved my problem.
Multiprocessing makes the function run as a separate process with its own memory. The memory is then cleared by the OS after the function is complete, which clears the memory leak. If you have memory leaks, this approach is likely to help.

I don't know if the copy works. Since I no longer work on that project, I also cannot check. 
However I don't think it will work, because the leaks seems to be caused in the underlying pdal library. You could verify this assumption using the track function in my snippet.

Also check if you run the latest version. This issue was closed, so I would assume that they added a fix for the bug.

**Comment by hobu** [comment]
> The fixed solved my problem.

Was the fix not in the version of the PDAL Python bindings you were using? The latest release was just last month that should have had it.

**Comment by AndreasDL** [comment]
I used the workaround to overcome the leak and that worked.
I work as a consultant, and have changed projects since I reported the bug.
I cannot test the new bindings as I no longer have bpf files and/or access to the code. 

If my snippet above did not produce a leak with the new bindings, then I guess it should be fine
