### ISSUE TITLE
RuntimeError: readers.las

### ISSUE THREAD

**Issue by bernardWeGroup** [PDAL/python#26]
I am trying to read a las file using the following code.

```
lidar_filename="LiDAR_DHMV_2_P2_ATL12213_ES_20150308_13043_9_71000_211000.laz"
b = polygon.bounds
print(b)
print(polygon.wkt)
cropper = {
    "pipeline": [ '/lidar/'+ lidar_filename,
        {   "type":"filters.crop",
            'bounds':str(([b[0], b[2]],[b[1], b[3]]))},
        {   "type":"filters.crop",
            'polygon':polygon.wkt},
        {   "type":"filters.hag"},
        {   "type":"filters.eigenvalues",
            "knn":16},
        {   "type":"filters.normal",
            "knn":16}
    ]}
pipeline = pdal.Pipeline(json.dumps(cropper))
pipeline.validate()
print(pipeline.execute())
%time n_points = pipeline.execute()
```

But I am getting an error during the read :
"RuntimeError: readers.las: reading point 1921300 of 1921285 total points"

What is a good way to debug such errors?

**Comment by jrobichaud** [comment]
Can you reproduce the problem using PDAL’s CLI?

I think this is more a problem with https://github.com/PDAL/pdal/issues itself than its python bindings.

**Comment by hobu** [comment]
> "RuntimeError: readers.las: reading point 1921300 of 1921285 total points

This is an LAZ file with a bad header or something. What does LAStools think of it?
