### ISSUE TITLE
how to install PDAL-Python with pdal1.9.1

### ISSUE THREAD

**Issue by EskApeeee** [PDAL/python#27]
pip python requires pdal itself beeing installed first  according to https://pdal.io.
I had downlord the PDAL1.9.1 and PDAL-python. So how to install PDAL without conda now?

**Comment by hobu** [comment]
PDAL-Python 2.3 has transitioned to using scikit-build and a pyproject.toml to define pip requirements at build time. Please repopen if the issue described in this ticket is still a problem.
