### ISSUE TITLE
pipeline.arrays empty when using numpy array input and multiple stages

### ISSUE THREAD

**Issue by chrislcs** [PDAL/python#31]
Hi,

I am trying to use PDAL within python to add some features to a point cloud. More specifically I am using `filters.eigenvalues`, `filters.normal`, and `filters.nndistance`. When using a reader in the pipeline (I used `readers.ept`) the pipeline works fine and the features get added and I can use `pipeline.arrays` to get the data. However when I try to run the same pipeline using a numpy structured array as input the pipeline executes but `pipeline.arrays` is empty.

```python
PDAL_PIPELINE = """
{
  "pipeline": [
    {
      "type": "filters.eigenvalues",
      "knn": 10
    },
    {
      "type": "filters.normal",
      "knn": 10
    },
    {
      "type": "filters.nndistance",
      "k": 10
    },
  ]
}
"""

pipeline = pdal.Pipeline(
    PDAL_PIPELINE,
    arrays=[point_cloud]
 )
pipeline.validate()
pipeline.execute()
result = pipeline.arrays
```

The input array looks like this:

```python
>>> point_cloud[0:1]
array([(122312.202, 489447.885, -0.23, 8, 1, 1, 1, 2, 30817)], dtype=[('X', '<f8'), ('Y', '<f8'), ('Z', '<f8'), ('Intensity', '<u2'), ('ReturnNumber', 'u1'), ('NumberOfReturns', 'u1'), ('Classification', 'u1'), ('UserData', 'u1'), ('PointSourceId', '<u2')])
```

If I use a writer stage the resulting file has the values for all dimensions of the input, but the dimensions created during the pipeline only contain 0s.

```
"Eigenvalue0";"Eigenvalue1";"Eigenvalue2";"NormalX";"NormalY";"NormalZ";"Curvature";"NNDistance";"X";"Y";"Z";"Intensity";"ReturnNumber";"NumberOfReturns";"Classification";"UserData";"PointSourceId"
0.000;0.000;0.000;0.000;0.000;0.000;0.000;0.000;122312.202;489447.885;-0.230;8.000;1.000;1.000;1.000;2.000;30817.000

```

I noticed all goes well when I only use 1 stage in the pipeline.

I am using a conda environment on ubuntu with python 3.7, PDAL 2.0.1, python-pdal 1.8.2, numpy 1.16.4.

**Comment by abellgithub** [comment]
This is a bug in the current python-pdal code.  I believe that it has been fixed in the unreleased code that's in the master branch of the repository.  If you wanted to try to build that, you should be OK, but note that the code in the master branch only works with PDAL 2.0+.

**Comment by chrislcs** [comment]
Alright I'll try that, thanks!

**Comment by abellgithub** [comment]
For posterity, the issue is that the reader that handles the numpy array is being attached to the last stage in the pipeline, rather than to the beginning of the pipeline.
