### ISSUE TITLE
the number of output ground points differs from another software

### ISSUE THREAD

**Issue by tangeroo** [PDAL/python#35]
@hobu 
Hi,
I got a classified laz file.I used PDAL and terrasolid to put out the ground points respectively .Obviously the number of ground points is less than the one from terrasolid.I don't know which one is right.Do you know how this happened?
Thanks
![image](https://user-images.githubusercontent.com/25971461/65134135-6212d000-da36-11e9-83f7-9176b7fa86a5.png)

**Comment by chambbj** [comment]
This will be your problem to solve, answering the question "Which one is right?". We make no claims to match terrasolid, and your pipeline includes filters that directly alter the number of points (voxel center nearest neighbors) and classifications (smrf).
