### ISSUE TITLE
OSError: Could not find pdal-config 'pdal-config.bat'

### ISSUE THREAD

**Issue by amelkikh** [PDAL/python#37]
`OS Win10`
`python v2.7`
`env conda`

Result:
```
(py27) D:\work\pdalextension>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    for item in get_pdal_config('--python-version').split():
  File "setup.py", line 68, in get_pdal_config
    'Could not find pdal-config %r: %s' % (pdal_config, ex))
OSError: Could not find pdal-config 'pdal-config.bat': [Error 2]
```

**Comment by hobu** [comment]
Python 2.7 isn't supported anymore for PDAL 2.0+

I thought we had a guard against the `pdal-config` check on windows in the script.

**Comment by amelkikh** [comment]
> Python 2.7 isn't supported anymore for PDAL 2.0+
> 
> I thought we had a guard against the `pdal-config` check on windows in the script.
Thx for quick reply.
Same problem using python 3.6.
There is no .bat files in repository

**Comment by hobu** [comment]
PDAL-Python 2.3 has transitioned to using scikit-build and a pyproject.toml to define pip requirements at build time. Please reopen if this ticket is still an issue.
