### ISSUE TITLE
In python - "RuntimeError: Couldn't create filter stage of type 'filters.python'."

### ISSUE THREAD

**Issue by ahalota** [PDAL/python#38]
Within a python script, I can't get "filters.python" to be recognized.

I import it into my code using:

`import pdal`

and constructed the following pipeline in my code:

```rangeAndSegmentPipeline = {
                "pipeline" : [
                        {
                            "type" : "readers.las",
                            "filename" : curFile
                        },
                        {   
                            "type"      : "filters.range",
                            "limits"    : "ScanAngleRank[-30:30]"
                        },
                        {   "type"      : "filters.splitter",
                            "length"    : lidarMetricsResolution,
                            "origin_x"  : minX,
                            "origin_y"  : minY,
                        },
                        {
                            "type"      : "filters.python",
                            "script"    : "pdal_filters.py",
                            "function"  : "saveIfMeetsPointDensityThreshold",
                            "module"    : "anything",
                            "pdalargs"  : "{ \"resolution\": "+str(lidarMetricsResolution)+", \"pulseDensity\" : "+str(pdensityThreshold)+"}",
                        }                        
                    ]
                }

pipeline = pdal.Pipeline(json.dumps(rangeAndSegmentPipeline))
            pipeline.validate()
```

And receive this error:

```
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\pdalEnv\lib\site-packages\pdal\pipeline.py", line 43, in validate
    return self.p.validate()
  File "pdal\libpdalpython.pyx", line 170, in pdal.libpdalpython.PyPipeline.validate
RuntimeError: Couldn't create filter stage of type 'filters.python'.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load.  Please see the FAQ at https://pdal.io/faq
```

The module is loaded from a conda environment I created called "pdalEnv". Within python, the imported version shows as 2.01.

Conda list outputs these items (among others):
`pdal                      2.0.1            py36h12372d9_5    conda-forge`
`python-pdal               2.2.2            py36hdc08f70_0    conda-forge`

If I run `pdal --drivers`, the output includes filters.python

If I run "pdal pipeline <mypipelinewithpython.json>", it works out fine. The issue only occurs if I am running within python.

`echo %PDAL_DRIVER_PATH%` shows:  
`C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\pdalEnv\Library\bin`

How else can I figure out what the issue is here?

**Comment by ahalota** [comment]
This issue occured on my Windows machine. 

This issue did not occur on a clean conda python environment set up on a linux machine.

**Comment by abellgithub** [comment]
Please see item 2 in the FAQ:

https://pdal.io/faq.html

**Comment by ahalota** [comment]
That doesn't resolve the issue in this case. The list of drivers does include filters.python, and I am able to run the pipeline just fine using pdal outside of python. 

It worked on my unix environment, but not Windows. I'll try a clean install on Windows soon and see if that fixes it, but otherwise I'm assuming it's some Windows issue.

**Comment by ahalota** [comment]
I looked into it more, not a Windows vs. Linux issue.

It seems to be a problem with running pdal-python from within my Eclipse environment (on either OS), works just fine outside of it with python run from the command line.
