### ISSUE TITLE
filters.elm hangs infinitely when passed a header-only .las

### ISSUE THREAD

**Issue by mviljamaa** [PDAL/python#48]
filters.elm hangs infinitely when passed a header-only .las.

It's possible that some other functions could hang as well, but I noticed it with filters.elm.

To recreate this, create a text file with ending .xyz (file ending probably not relevant) with content:

`X,Y,Z,scan_angle\n`

Where there's a newline \n / enter after the header.

Then use the following code to convert it to .las and then try to pass it through filter.elm.

```
import pdal
import json

inputfile = "yourpathto\\haltinput.xyz"
outputfile = "yourpathto\\haltoutput.las"

xyztolas = \
{
  "pipeline": [
    {
      "type": "readers.text",
      "filename": "yourpathto\\haltinput.xyz",
    },
    {
      "type": "writers.las",
      "filename": "yourpathto\\haltinput.las"
    }
  ]
}

# tree extraction
haltdict = \
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "yourpathto\\haltinput.las"
    },
    {
      "type": "filters.elm",
    },
    {
      "type": "writers.las",
      "filename": "yourpathto\\haltoutput.las"
    }
  ]
}

somepipeline = json.dumps(xyztolas)

pipeline = pdal.Pipeline(somepipeline)
pipeline.validate()
count = pipeline.execute()

somepipeline = json.dumps(haltdict)

pipeline = pdal.Pipeline(somepipeline)
pipeline.validate()
count = pipeline.execute() # enters infinite loop
```

**Comment by chambbj** [comment]
Thanks for the report. I can replicate this, but it's an issue in the main PDAL library (nothing specific to Python). I'll ticket it over there.
