### ISSUE TITLE
OSError: Could not find pdal-config 'pdal-config': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dlliyang** [PDAL/python#5]
Collecting PDAL
  Downloading https://files.pythonhosted.org/packages/b5/21/456d7f7e3081a32e7c8852f78a813dcf3757000b0623371f125a4c3f78a8/PDAL-2.0.0.tar.gz (51kB)
    100% |████████████████████████████████| 61kB 390kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LMN24R/PDAL/setup.py", line 124, in <module>
        for item in get_pdal_config('--python-version').split():
      File "/tmp/pip-build-LMN24R/PDAL/setup.py", line 68, in get_pdal_config
        'Could not find pdal-config %r: %s' % (pdal_config, ex))
    OSError: Could not find pdal-config 'pdal-config': [Errno 2] No such file or directory
how to solve this?thanks!

**Comment by hobu** [comment]
The PDAL Python bindings require [PDAL](https://pdal.io) to be installed.

**Comment by manuyesudas1991** [comment]
Hi im getting same error whil installing pdal
