### ISSUE TITLE
writers.ept_addon crashes when running validate using PDAL/python

### ISSUE THREAD

**Issue by jrobichaud** [PDAL/python#50]
When running a pipeline using `writers.ept_addon` using PDAL/python, it will crash. Running the same pipeline with PDAL's cli it will work.

I made this Github project to reproduce the bug clearly:
https://github.com/jrobichaud/pdal-entwine-addon-bug-report

You can compare the executions on travis-ci:
https://travis-ci.org/jrobichaud/pdal-entwine-addon-bug-report/builds/654974654

**Comment by hobu** [comment]
I think this might have already been reported by @normanb in the PDAL repo.

**Comment by jrobichaud** [comment]
I renamed the issue. @hobu I do not find the issue you are referring.

Feel free to close my issue if it is a duplicate.

**Comment by hobu** [comment]
We might have been discussing it on chat or at the sprint. I don't remember the particulars. It is indeed an issue that will hopefully be fixed when we release PDAL 2.1 around the end of next month.

**Comment by normanb** [comment]
https://github.com/PDAL/PDAL/issues/2891

**Comment by hobu** [comment]
This should have been fixed with the PDAL 2.1 and PDAL-Python 2.3 combo. Please reopen if it is not.
