### ISSUE TITLE
How to load data into memory tile wise

### ISSUE THREAD

**Issue by digital-idiot** [PDAL/python#51]
`pdal` can be used to split large las/laz file into multiple square tiles in the form of file (https://pdal.io/apps/tile.html). 
* Is it possible to load each tile individually into memory for custom processing without writing into file?
* Is it possible to make tiles rectangular?
* What about partially overlapping tiles?

**Comment by abellgithub** [comment]
You will have to be more specific about what you want to do.

Thanks,

**Comment by hobu** [comment]
We use entwine.io for these kinds of workflows. Please use github for bugs and tickets. Use the [mailing list](https://pdal.io/community.html#mailing-list) for discussion topics like this one.
