### ISSUE TITLE
Problem with invalid JSON when calling filters.hag Delauney triangulation via Python

### ISSUE THREAD

**Issue by AndrewCunliffe** [PDAL/python#52]
I would like to use the Delaunay triangulation in the filters.hag, but have not found a way to implement this with Python (PDAL v2.0.1, Windows 64, Python 3.7).

Without calling "delaunay": true AND count >1, the code below returns height above ground relative to the closest ground point. The code fails when trying to call the Delaunay function to compute heights relative to an interpolated surface with a count >1, I think because the resultant JSON is invalid. 

> "delaunay": true
 
fails with "NameError: name 'true' is not defined" because it is not a Python boolean constants

> "delaunay": True
> "delaunay": 'true'
 
fails with "Process finished with exit code -1073740791 (0xC0000409)" when the pipeline is executed

This appears to be an issue with json.dumps() failing to translate Python's 'True' into JSON 'true'.

- Can this be resolved within python?
- Would it be possible, and useful, to update .validate() to check for invalid JSONs being supplied to PDAL?

```
import pdal
import json

input_file = ("C:/Example_AC.laz")
outfile = ("C:/Example_AC_HAG.laz")

hag_pipeline = [
    {
        "type": "readers.las",
        "filename": input_file
    },
    {
        "type": "filters.hag",
        "delaunay":True,
        "count": 8
    },
    {
        "type": "filters.ferry",
        "dimensions": "HeightAboveGround=Z"
    },
    {
        "type": "writers.las",
        "filename": outfile,
        "forward": "all"
    }
]

hag_pipeline = pdal.Pipeline(json.dumps(hag_pipeline))  # convert pipeline into JSON format
hag_pipeline.validate()  # validate the PDAL pipeline
hag_pipeline.execute()  # run the PDAL pipeline'
```

**Comment by abellgithub** [comment]
No.  You're providing a JSON pipeline, not Python.  Your JSON must be valid in order to be processed.  I would also suggest that you don't place python comments in your JSON as it masks other errors in your JSON pipeline specification.

I would suggest that you run the pipeline outside of python.  Once you get it right, you can embed it in python and modify it as necessary.

**Comment by abellgithub** [comment]
Oops.  I see an error in the example.  For some reason there are still a set of braces around the array that is the pipeline.  Be sure to remove those in your pipeline.

**Comment by AndrewCunliffe** [comment]
Thanks for the suggestions, I really appreciate your help.

Working from the exampling you [linked](https://pdal.io/python.html), I understand that one option to circumvent possible issues with the invalid JSON string from json.dumps() is specifying a string. 

This works for the simple HAG

```
hag_pipeline = """
[
    {
        "type": "readers.las",
        "filename": "C:/workspace/DroneAllometry/inputs/Example_AC.laz"
    },
    {
        "type": "filters.hag"
    },
    {
        "type": "filters.ferry",
        "dimensions": "HeightAboveGround=Z"
    },
    {
        "type": "writers.las",
        "filename": "C:/workspace/DroneAllometry/testing/Example_AC_HAG.laz",
        "forward": "all"
    }
]
"""

hag_pipeline = pdal.Pipeline(hag_pipeline) 
hag_pipeline.validate() 
hag_pipeline.execute()
```

But this doesn't work for the Delaunay HAG

```
hag_pipeline = """
[
    {
        "type": "readers.las",
        "filename": "C:/workspace/DroneAllometry/inputs/Example_AC.laz"
    },
    {
        "type": "filters.hag",
        "delaunay": true,
        "count": 8
    },
    {
        "type": "filters.ferry",
        "dimensions": "HeightAboveGround=Z"
    },
    {
        "type": "writers.las",
        "filename": "C:/workspace/DroneAllometry/testing/Example_AC_HAG.laz",
        "forward": "all"
    }
]
"""

hag_pipeline = pdal.Pipeline(hag_pipeline) 
hag_pipeline.validate() 
hag_pipeline.execute()
```

Do you have any more hints?

**Comment by abellgithub** [comment]
The delaunay hag was broken in 2.0.1.  It would crash.  But it has been fixed.  I have no problems with this pipeline on the current 2.0-maintenance branch.  You'll have to build PDAL from source or use a suitable docker image in order to get it to work.

**Comment by abellgithub** [comment]
Here is the ticket: https://github.com/PDAL/PDAL/issues/2805

**Comment by AndrewCunliffe** [comment]
Ah, well that is very useful to know to stop me going further in the wrong direction!

Is there any provisional timeframe for the next version release via Conda with your November fix?
