### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by defreturn** [PDAL/python#53]
Hi there!

Getting the following error from pip install PDAL:

> Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-TKRyJ4/PDAL/setup.py", line 30, in <module>
        from packaging.version import Version
    ImportError: No module named packaging.version
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TKRyJ4/PDAL/

> 

Trying to install it on Ubuntu Beaver

**Comment by hobu** [comment]
At the moment you need packaging, numpy, cython, and setuptools installed to build and install PDAL's python extension from source.
