### ISSUE TITLE
Access to faces in python?

### ISSUE THREAD

**Issue by dmfenton** [PDAL/python#58]
I'm attempting to create a python notebook where I do the following:
1. run poisson reconstruction in pdal
2. enrich the new point cloud w/ additional data
3. write out a ply file with faces

However, the ply file does not include any faces and so I am left with a point cloud when I want a mesh. Am I doing something wrong here or is this unsupported?

**Comment by hobu** [comment]
Nope, not supported at the moment. If you muck with the cython, you should be able to expose them from the PointView, however.

**Comment by hobu** [comment]
If you write a pipeline, you'll be able to write it to an actual file and then use some other PLY reader to get back the faces. Not ideal, but cheap hackery.

**Comment by dmfenton** [comment]
Thanks for the quick response @hobu. Despite this roadblock I'm finding PDAL to be super fun and easy to work with.

**Comment by hobu** [comment]
Reopen with a PR or if you are stuck with something.
