### ISSUE TITLE
Cannot find proj.db in Conda

### ISSUE THREAD

**Issue by karl-magnus** [PDAL/python#59]
Hi!
I'm trying to run a pipline in QGIS python console. When I invoke a pipeline with "spatialreference":  or try to read from pg_pointcloud I get an error.

`Traceback (most recent call last):
  File "C:\Users\ikmjo01\Anaconda3\envs\pdalworkshop\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 28, in <module>
  File "C:\Users\ikmjo01\Anaconda3\envs\pdalworkshop\lib\site-packages\pdal\pipeline.py", line 40, in execute
    return self.p.execute()
  File "libpdalpython.pyx", line 166, in pdal.libpdalpython.PyPipeline.execute
RuntimeError: Could not import coordinate system 'EPSG:3008': PROJ: proj_create_from_database: Cannot find proj.db.`

If I read just from a LAS-file without "spatialreference" it works and the pipeline works fine with  "spatialreference" in Conda prompt. I've tried to set the env-variable to where proj.db resides, reactivate the env but without success. Anything else to try?

`conda env config vars set PROJ_LIB=C:\Users\ikmjo01\Anaconda3\envs\pdalworkshop\Library\share\proj`

On Windows as you see and pdal, qgis installed with Anaconda3.
Regards

**Comment by abellgithub** [comment]
If you're using PROJ 7, it should find the DB automatically.  If you're using PROJ 6.X, conda normally sets the environment variable PROJ_LIB for you.  Have you checked the state of that variable?  Do you have some local libproj installed that may be getting found?

**Comment by karl-magnus** [comment]
Seems like PROJ 7 in the package list. It was updated from 6.3 today when I updated pdal. Then I installed QGIS in the same env. Could that cause issues?
State of the variable. Seems ok.
`(pdalworkshop) C:\projekt\3d\las>conda env config vars list
PROJ_LIB = C:\Users\ikmjo01\Anaconda3\envs\pdalworkshop\Library\share\proj`

**Comment by hobu** [comment]
Yes, QGIS could have messed with PROJ_LIB environment variables. Does it work in a clean environment?

**Comment by abellgithub** [comment]
If PROJ_LIB is set and points to the right place, I'm not sure how this couldn't work unless there's something about QGIS that's clearing the environment.  But it should also work with PROJ 7 without any env. variable.

**Comment by hobu** [comment]
> I'm not sure how this couldn't work unless there's something about QGIS that's clearing the environment.

Conda has that weird environment cascading thing. The PROJ packages activate.bat could be getting called multiple times and maybe it has a bug in it.

**Comment by karl-magnus** [comment]
Some more testing. It works when just running the Python script in Conda. But running the code from the python console within QGIS it doesn't. And that was what I would like to do. Some difference in how PROJ is accessed. Maybe a QGIS problem then.

**Comment by hobu** [comment]
Can you file a new ticket at https://github.com/conda-forge/proj.4-feedstock and refer to this one? The details about QGIS + PDAL vs PDAL-alone is the important thing to describe.
