### ISSUE TITLE
python2.7 pip install error

### ISSUE THREAD

**Issue by wemamawe** [PDAL/python#6]
i'm using ubuntu16.7 ,and python2.7 
already installed cython and packaging
but when i install pdal==2.0, there is an error.

 File "setup.py", line 124, in <module>
    for item in get_pdal_config('--python-version').split():
  File "setup.py", line 68, in get_pdal_config
    'Could not find pdal-config %r: %s' % (pdal_config, ex))
OSError: Could not find pdal-config 'pdal-config': [Errno 2] No such file or directory

**Comment by hobu** [comment]
PDAL must be installed and pdal-config in your path for the Python extension to find where to compile and install.
