### ISSUE TITLE
libpdalpython.pyx- RuntimeError

### ISSUE THREAD

**Issue by ioanna-tsak** [PDAL/python#65]
I want to execute the following pipeline and I get the error below:
```
k = """
    {
        "pipeline": [
            "%s/outputs/%s/cloud_%s.pcd",
            {
                "type": "filters.normal",
                "knn": 8
            }
        ]
    }""" % (
        out,
        id,
        id,
    )
pipeline = pdal.Pipeline(k)
pipeline.validate()
pipeline.execute()
```

`.....
File "/usr/local/lib/python3.6/dist-packages/pdal/pipeline.py", line 40, in execute
    return self.p.execute()
  File "libpdalpython.pyx", line 166, in pdal.libpdalpython.PyPipeline.execute
RuntimeError: FIELDS were specified more than once`

Any idea on how could this be resolved?

**Comment by hobu** [comment]
Try removing the `validate()` call.

**Comment by abellgithub** [comment]
I believe this is a data issue, so it would be helpful to have the header of your PCD file.

**Comment by ioanna-tsak** [comment]
> Try removing the `validate()` call.

This worked! Thank you!

**Comment by ioanna-tsak** [comment]
> I believe this is a data issue, so it would be helpful to have the header of your PCD file.
Even though the answer of @hobu resolved my problem, I post the header as you asked. 
```

# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
COUNT 1 1 1
WIDTH 1821
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1821
DATA ascii

```
