### ISSUE TITLE
RuntimeError: Couldn't create filter stage of type 'filters.python'.

### ISSUE THREAD

**Issue by jiawenquan** [PDAL/python#8]
json = """
{
  "pipeline":[
    {
      "filename":"test/data/1.2-with-color.las",
      "spatialreference":"EPSG:2993"
    },
    {
      "type":"filters.python",
      "function":"filter",
      "source":"import numpy as np\n\ndef filter(ins,outs):\n\tcls = ins['Classification']\n\n\tkeep_classes = [1]\n\n\t# Use the first test for our base array.\n\tkeep = np.equal(cls, keep_classes[0])\n\n\t# For 1:n, test each predicate and join back\n\t# to our existing predicate array\n\tfor k in range(1,len(keep_classes)):\n\t\tt = np.equal(cls, keep_classes[k])\n\t\tkeep = keep + t\n\n\touts['Mask'] = keep\n\treturn True",
      "module":"anything"
    },
    "out2.las"
  ]
}"""

pipeline = pdal.Pipeline(json)
count = pipeline.execute()

![image](https://user-images.githubusercontent.com/18283636/41762631-f1d6f496-762d-11e8-931b-db86dc97f3bd.png)

**Comment by chambbj** [comment]
It is not the source of your error, but your pipeline is invalid. The first stage should include the reader type, i.e., `"type":"readers.las"`.

Before running `pipeline.execute()` it's a good idea to run `pipeline.validate()` as well.

Now, to your error, you'll need to tell us how you've installed PDAL and it's Python extension.

**Comment by jiawenquan** [comment]
I installed it through coanda
![image](https://user-images.githubusercontent.com/18283636/41772342-d079264e-764a-11e8-969c-a7313648397e.png)

This is a great open source project 
thank!!

**Comment by chambbj** [comment]
Okay, that's helpful. Can you provide the outputs of both `conda info` and `conda list`?

**Comment by jiawenquan** [comment]
![image](https://user-images.githubusercontent.com/18283636/41772552-9f03d702-764b-11e8-83bb-d8adec9cd813.png)

![image](https://user-images.githubusercontent.com/18283636/41772784-94466388-764c-11e8-9f47-a55a39782029.png)
![image](https://user-images.githubusercontent.com/18283636/41772878-d7178048-764c-11e8-8a56-0ce4bdf804f6.png)
![image](https://user-images.githubusercontent.com/18283636/41772927-ff0c95f2-764c-11e8-9d94-e5e061023eaf.png)

[piplist.txt](https://github.com/PDAL/python/files/2127327/piplist.txt)

**Comment by jiawenquan** [comment]
I tried all “filters.python” and it was this error

**Comment by chambbj** [comment]
Looks like you also tried to install the python extension via pip (this
shows up as PDAL 2.0.0). Uninstall this, then install `python-pdal` using
conda from the same conda-forge channel you used to install `pdal`.

**Comment by jiawenquan** [comment]
![image](https://user-images.githubusercontent.com/18283636/41775205-9b3f595c-7655-11e8-9dd1-aa6ba2286d2f.png)

data_json = """
{
  "pipeline":[
    {
      "filename":"test/data/las/1.2-with-color.las",
      "spatialreference":"EPSG:2993"
    },
    {
      "type":"filters.python",
      "function":"filter",
      "source":"import numpy as np\n\ndef filter(ins,outs):\n\tcls = ins['Classification']\n\n\tkeep_classes = [1]\n\n\t# Use the first test for our base array.\n\tkeep = np.equal(cls, keep_classes[0])\n\n\t# For 1:n, test each predicate and join back\n\t# to our existing predicate array\n\tfor k in range(1,len(keep_classes)):\n\t\tt = np.equal(cls, keep_classes[k])\n\t\tkeep = keep + t\n\n\touts['Mask'] = keep\n\treturn True",
      "module":"anything"
    },
    "test/temp/out2.las"
  ]
}
"""

pipeline = pdal.Pipeline(data_json)
pipeline.validate()
count = pipeline.execute()


![image](https://user-images.githubusercontent.com/18283636/41775627-3f5a163e-7657-11e8-877d-e28df3c73276.png)

The same question

**Comment by chambbj** [comment]
Any chance you have another version of PDAL installed? Perhaps you tried building from source or grabbed another distribution, and that version is being detected before the Conda installed version.

Please share outputs of `pdal --version`, `pdal --drivers`, and `echo %PDAL_DRIVER_PATH%`.

**Comment by chambbj** [comment]
And have you tried running again now? After uninstalling OSGeo4W? I see in your third screenshot that it did in fact locate `filters.python`.

**Comment by jiawenquan** [comment]
I tried again
The same Error

Now I'm going to create a new Conda environment and try again

**Comment by chambbj** [comment]
I think that's your best bet. I have no idea what has happened to the environment you are working in, but something about it seems corrupt.

**Comment by jiawenquan** [comment]
```
{
  "pipeline":[
      "C:/Users/Administrator/Desktop/test/1.2-with-color.las",
      {
          "type": "filters.smrf"
      },
      {
          "type": "filters.python",
          "module": "anything",
          "function": "fff",
          "source": "def fff(ins,outs):\n\tX = ins['X']\n\touts['X']=X*10\n\treturn True"
      },
      {
          "type": "writers.las",
          "filename": "file-filtered.las"
      }
  ]
}
```

My computer is windows10
I tried running DOS


It's going to stay stuck，And then run it empty



Other filters pipeline is normal
Only `filters. Python`  Error
I think it's a lack of dependency projects

**Comment by chambbj** [comment]
It is also suspicious that the new one is back at PDAL v1.7.1 (should be
v1.7.2) with no PDAL_DRIVER_PATH set.

How are you creating the new conda environment?

**Comment by jiawenquan** [comment]
The environment I created through PyCharm，
It did go back to 1.71，I did the upgrade again to 1.71
Do other people have the same problem?

**Comment by jiawenquan** [comment]
Thank you very much.I found the specific reason, which is a Pycharm text compiler problem.
```
{
  "pipeline":[
    {
      "filename":"1.2-with-color.las",
      "spatialreference":"EPSG:2993"
    },
        {
            "type": "filters.python",
            "function": "fff",
            "source": "import numpy as np\ndef fff(ins,outs):\n\tX = ins['X']\n\touts['X']=X*10\n\treturn True"
        },
    "out2.las"
  ]
}
```
I'll just write json  dos run: `pdal pipeline reproject.json`  is ok,
But in pyCharm text is Error，
I think this is because python errors in json are parsed in pycharm text，

I hope it's adaptive！！
Thank you very much for your patience and help！！

**Comment by chambbj** [comment]
Closing this issue, as it sounds like you at least have a working environment complete with `filters.python`. If you are having other issues, please open a new ticket.

**Comment by chobm** [comment]
I'm having the same issue. I created an evironment using 
`conda create -n pdalenv -c conda-forge python-pdal pdal=1.7.2 python=3.6`,
`pdal --drivers` is listing `filters.python` as available. But when I try to run the example from [pdal.io](https://pdal.io/stages/filters.python.html), I get the same error message:
![grafik](https://user-images.githubusercontent.com/41343405/42837558-afbdbfc4-89fe-11e8-8a5e-0bde76f5efbf.png)
Can anybody help? Thanks a lot!
