### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by fluviotect** [PDAL/python#85]
I got  an import error running your second example in Jupyter Lab (Py 3.7 Win7x64).

I crossed-referenced packages in my Conda env with dependencies listed on your GitHub page and two were missing:
- cython
- scikit-build

So it seems when I installed pdal, some but not all of the dependencies missing from my env were identified and/or installed. 

If it matters, to install pdal, I used:  

> conda install -c conda-forge python-pdal 

Attempting to resolve, I installed the two missing packages (and their dependencies). However, I still get the same error when I run notebook.

> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-427772ed169a> in <module>
>      12     }"""
>      13 
> ---> 14 import pdal
>      15 import numpy as np
>      16 pipeline = pdal.Pipeline(json % data)
> 
> C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\pdal\__init__.py in <module>
>       1 __version__='2.3.6'
>       2 
> ----> 3 from .pipeline import Pipeline
>       4 from .array import Array
>       5 from .dimension import dimensions
> 
> C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\pdal\pipeline.py in <module>
>       1 
> ----> 2 from pdal import libpdalpython
>       3 import numpy as np
>       4 
>       5 class Pipeline(object):
> 
> ImportError: DLL load failed: The specified procedure could not be found.

**Comment by hobu** [comment]
> I crossed-referenced packages in my Conda env with dependencies listed on your GitHub page and two were missing:
> * cython
> * scikit-build

Were these needed to *run* the PDAL Python bindings or just to build? They are requirements for building, but they shouldn't be for running.

When I create a fresh environment, `python -m pdal` works fine for me on Win10:

```
conda create -n issue-85
conda activate issue-85
conda install python=3.7 python-pdal
```

```
(issue-85) C:\Users\hobu\Desktop>python -m pdal
C:\Miniconda3\envs\issue-85\python.exe: No module named pdal.__main__; 'pdal' is a package and cannot be directly executed
```

It seems your environment is resolving an older python-pdal package. You should try to upgrade just that.

```
python-pdal               2.4.0            py37h0b66150_2    conda-forge
```
