### ISSUE TITLE
How to get filters. Python custom 'Mask' value

### ISSUE THREAD

**Issue by jiawenquan** [PDAL/python#9]
```
import numpy as np

def fff(ins,outs):
  X = ins['X']
  Result = np.equal(X, 637501.67)
  #print X
  #print Mask
  outs['Mask'] = Result
  return True
```
I finished this pipeline
How do I get the value for 'Mask'
------
```
import numpy as np

def fff(ins, outs):
    xyzmin = np.min([ins['X'], ins['Y'], ins['Z']], axis=0)
    xyzmax = np.max([ins['X'], ins['Y'], ins['Z']], axis=0)
    centerxyz = (xyzmin + xyzmax) / 2
    outs['center'] = centerxyz
    # 八叉树分割点云
    npxyz = np.array([ins['X'], ins['Y'], ins['Z'], ins['Red'], ins['Green'], ins['Blue']])
    octree1 = npxyz[np.where((ins['X'] <= centerxyz[0]) & (ins['Y'] <= centerxyz[1]) & (ins['Z'] <= centerxyz[2]))]  # 1
    octree2 = npxyz[np.where((ins['X'] < centerxyz[0]) & (ins['Y'] > centerxyz[1]) & (ins['Z'] < centerxyz[2]))]  # 2
    octree3 = npxyz[np.where((ins['X'] > centerxyz[0]) & (ins['Y'] > centerxyz[1]) & (ins['Z'] < centerxyz[2]))]  # 3
    octree4 = npxyz[np.where((ins['X'] > centerxyz[0]) & (ins['Y'] < centerxyz[1]) & (ins['Z'] < centerxyz[2]))]  # 4
    octree5 = npxyz[np.where((ins['X'] < centerxyz[0]) & (ins['Y'] > centerxyz[1]) & (ins['Z'] > centerxyz[2]))]  # 5
    octree6 = npxyz[np.where((ins['X'] > centerxyz[0]) & (ins['Y'] > centerxyz[1]) & (ins['Z'] > centerxyz[2]))]  # 6
    octree7 = npxyz[np.where((ins['X'] < centerxyz[0]) & (ins['Y'] < centerxyz[1]) & (ins['Z'] > centerxyz[2]))]  # 7
    octree8 = npxyz[np.where((ins['X'] > centerxyz[0]) & (ins['Y'] < centerxyz[1]) & (ins['Z'] > centerxyz[2]))]  # 8
    outs['octree1'] = octree1
    outs['octree2'] = octree2
    outs['octree3'] = octree3
    outs['octree4'] = octree4
    outs['octree5'] = octree5
    outs['octree6'] = octree6
    outs['octree7'] = octree7
    outs['octree8'] = octree8
    return True
```
I want to split the point cloud by pipeline `octree`，
Save each segmented data separately
I don't know if it can be done

**Comment by chambbj** [comment]
To your first question, see https://pdal.io/stages/filters.python.html#predicates. Points whose mask value is true are retained, otherwise they are dropped. Mask is a special dimension -- it is not returned/used outside of the Python filter.

As for the second, `filters.python` currently requires

> Each array contains all the Dimensions of the incoming `ins` point schema. Each array in the `outs` list match NumPy array of the same type as provided as `ins` for shape and type.

So as things stand currently, you could not return a split cloud. You could almost certainly return a dimension that encodes the octree indexing and split on that dimension outside of the filter.

**Comment by jiawenquan** [comment]
### thank you！

**Comment by jiawenquan** [comment]
Thank you again！
I implemented the point cloud split through the pipeline `octree`，
you know，I need to `filters.range` `pipeline` **eight** times，
It takes a long time，
If you feel that octree is necessary, I think you can add "filters. octree".

**Comment by chambbj** [comment]
I'm guessing that you have had to use tag and inputs to make all of this
work. Those effectively create multiple paths through the pipeline, so you
are likely running some stages multiple times. We are happy to accept pull
requests, so if you come up with a `filters.octree`, just let us know (over
at PDAL/PDAL of course)!  Can we close this issue now?

**Comment by jiawenquan** [comment]
yes，close this issue
